# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyLiveWidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyLiveWidgetExtension
  #pod 'SDWebImageSwiftUI'

end

target 'WBLiveActivityUpdateDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WBLiveActivityUpdateDemo
  #pod 'SDWebImageSwiftUI'

end
